version: '3.8'
services:
  app:
    image: isgroup-register
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    ports:
      - "8001:8000"